### ISSUE TITLE
AZP.DragonRider:IsDragonRiding failing?

### ISSUE THREAD

**Issue by ferib** [AzerPUG/DragonRiding#10]
hi, I noticed you check some buffs _(which appear to be dragon-riding compatible mount spells )_ to see if dragon riding is active but it doesn't seem to work for me.

```lua
function AZP.DragonRider:IsDragonRiding()
    for i = 1, 40 do
        local name, _, _, _, _, _, _, _, _, SpellID = UnitBuff("PLAYER", i)
        if SpellID == nil then return false end
        if SpellID == 368896 or SpellID == 368899 or SpellID == 360954 or SpellID == 368901 then
            return true
        end
    end
    return false
end
```

Any chance you can replace it with

```lua
local isFlying, isDragonMounted, speed = C_PlayerInfo.GetGlidingInfo()
```

as `isDragonMounted` indicates you are mounted on a dragon riding compatible mount.

**Comment by Arco-Dielhof** [comment]
I will have a look at it somewhere shortly.
Did it work fine before the patch, by any chance?

It is curious that it does not work for you. I will have to look into that as well. I should have time in the weekend.
Thanx for bringing this to our attention :D

**Comment by ferib** [comment]
I only learned dragin riding yday evening and haven't had time to test today yet, so not sure if i screwd something up. Anyway I noticed that you check for 4 specific buffs, which appear to be different dragon riding mounts, so it might be benificial to use the `C_PlayerInfo.GetGlidingInfo` API as showen in #11

**Comment by ferib** [comment]
Quick note, I looked into this again and it DOES work. I don't know why I got confused but I think the AddOn UI was not visible (obscured) by other addon frames lol.

Anyway, I believe `C_PlayerInfo.GetGlidingInfo` is still an improvement as you do not need to keep track of all dragon riding mounts anymore ;D.

**Comment by Arco-Dielhof** [comment]
Glad it does actually work!

I agree, it is an improvement, and I will (with less priority now that it is not actually broken) still get it changed some where soon! Thanx!

Where did you find the function?

**Comment by ferib** [comment]
> Where did you find the function?

Reverse engineered the client to figure out why the heck I was disconnecting on dragon flying. Found some nice properties in the player object that were connected to that Lua API. 

FYI the third value is numeric that represents the movement speed (total velocity of forward/upwards). You can calculate the movement speed by `local _, _, speed = C_PlayerInfo.GetGlidingInfo(); return speed * 7`. Might be another cool feature to add to the GUI.
