### ISSUE TITLE
Addon broken

### ISSUE THREAD

**Issue by mattyzee2023** [AzerPUG/DragonRiding#14]

**Comment by mattyzee2023** [comment]
Addons stopped working with 10.1. Vigor when not dragonriding always sets to 0 now

**Comment by Arco-Dielhof** [comment]
Able to replicate it, probably something changes in the API that is not yet adjusted for in the AddOn.
Looking into it today, I hope to have an update somewhere tonight / tomorrow. (Goal, not promise :P )
