### ISSUE TITLE
Request to add scaling

### ISSUE THREAD

**Issue by allcoast** [AzerPUG/DragonRiding#2]
Feature request to add a scale option so we can adjust the size of the UI bubbles.

**Comment by Arco-Dielhof** [comment]
This feature had to be postponed a bit due to other more important fixes and something that came up privately. It is still on the list to do, though!

**Comment by Arco-Dielhof** [comment]
This feature is coming out in the next version, which should be downloadable through CurseForge somewhere tomorrow at the latest!
