### ISSUE TITLE
LUA error when entering garrison

### ISSUE THREAD

**Issue by hollo6** [AzerPUG/DragonRiding#3]
189x ...eAzerPUGsDragonRider/AzerPUGsDragonRider.lua:247: attempt to index a nil value
[string "@AzerPUGsDragonRider/AzerPUGsDragonRider.lua"]:247: in function `GetRechargePercent'
[string "@AzerPUGsDragonRider/AzerPUGsDragonRider.lua"]:189: in function `FillVigorFrame'
[string "@AzerPUGsDragonRider/AzerPUGsDragonRider.lua"]:277: in function <...eAzerPUGsDragonRider/AzerPUGsDragonRider.lua:277>

Locals:
self = <table> {
 IsDragonRiding = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:225
 ZoneChanged = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:258
 FillVigorFrame = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:188
 OnLoad = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:17
 OnEvent = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:323
 ChechChangeLogData = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:314
 BuildOptionsPanel = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:88
 SavePosition = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:236
 BuildVigorFrame = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:25
 CreateChangeLog = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:290
 GetCurrentVigor = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:254
 GetMaxVigor = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:250
 LoadPosition = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:241
 GetRechargePercent = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:246
 Show = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:160
 Hide = <function> defined @AzerPUGsDragonRider/AzerPUGsDragonRider.lua:170
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index a nil value"

**Comment by hollo6** [comment]
and the same just happened after being teleported to mulgore during a campaign quest.

**Comment by hollo6** [comment]
It keeps spamming this error whenever zoning out of Dragon Isles, can only be fixed by UI reload.

**Comment by Arco-Dielhof** [comment]
A bit later then hoped for, but a version is now live on CurseForge to have a fix for this!
