### ISSUE TITLE
frame keeps moving

### ISSUE THREAD

**Issue by hollo6** [AzerPUG/DragonRiding#5]
Is it possible to have the addon not move the frame? (A quick workaround editing the functions moving it would be fine for now.)
I have moved it with MoveAnything to be able to scale it but it is constantly being moved back and forth and getting resized.
Thanks!

**Comment by Arco-Dielhof** [comment]
You should move our AddOn manually, by just dragging it to another place.
MoveAnything has no access to the SavedVariables of other AddOns, and we save it in that to make sure it remembers the location. If you move our AddOn properly, by the AddOn itself, it will be saved and should stay in the location,

Generally, using MoveAnything is only a good idea on Blizzard frames, not on other AddOns. The name is kinda misleading like that.

**Comment by hollo6** [comment]
Sorry if my description wasn't clear enough.
I'm moving the Power Bar frame with MA which shows vigor. It changes to this addon's frame when unmounting which is expected.
What is not expected is that the original Power Ability Bar keeps changing location and size, sometimes shifting down every time when dismounting so it's totally out of place after a little while.
Is there something that can be done about this?

**Comment by Arco-Dielhof** [comment]
I am sorry for misunderstanding.

The native bar is controlled by the Blizzard API and was extremely hard to adjust and even when managed, kept changing, so we decided not to touch it and instead remake it as a custom frame that we could 100% control.

So the vigor frame you see when mounted and when dismounted, are actually 2 entirely different frames. One controlled only by Blizzard, and one controlled by us.

We only have control over our own AddOn's frame, not over anothwr AddOns frame, nor the Blizzard's Native one.

(I hope I understand correctly this time, maybe answering right before bed is not my smartest choice 😂)

**Comment by hollo6** [comment]
Yes you get it now :) So my problem is, even though this addon shouldn't interfere with the native frame, it still does. Often, but not always, when this separate frame is being hidden (mounting), the native frame gets shifted off of its place.

**Comment by hollo6** [comment]
So, is there a way to fix this? Maybe an option to resize the frame with this addon?

**Comment by Arco-Dielhof** [comment]
I added it several weeks ago, but it seems something has gone wrong and it did not make it to CF somehow... Putting update out now!

**Comment by hollo6** [comment]
With the new version, I get the following error report on every login/reload and the frame is not being shown at all.

4x ...eAzerPUGsDragonRider/AzerPUGsDragonRider.lua:372: attempt to index upvalue 'CustomVigorFrame' (a nil value)
[string "@AzerPUGsDragonRider/AzerPUGsDragonRider.lua"]:372: in function <...eAzerPUGsDragonRider/AzerPUGsDragonRider.lua:370>
[string "=[C]"]: in function `SetValue'
[string "@AzerPUGsDragonRider/AzerPUGsDragonRider.lua"]:381: in function <...eAzerPUGsDragonRider/AzerPUGsDragonRider.lua:377>

Locals:
self = VigorFrameScaleSlider {
 0 = <userdata>
 NineSlice = Frame {
 }
 Thumb = VigorFrameScaleSliderThumb {
 }
 tooltipText = "Scale for mana bars"
 Text = VigorFrameScaleSliderText {
 }
 High = VigorFrameScaleSliderHigh {
 }
 Low = VigorFrameScaleSliderLow {
 }
}
scale = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'CustomVigorFrame' (a nil value)"
CustomVigorFrame = nil

**Comment by hollo6** [comment]
Also, even if I hardcode some value for the scale, the frame moves back to the middle of the screen when mounting.
