### ISSUE TITLE
Leaking Global "TestVar"

### ISSUE THREAD

**Issue by mbattersby** [AzerPUG/DragonRiding#7]
I think this is forgotten debug code:

    TestVar = C_UIWidgetManager.GetStatusBarWidgetVisualizationInfo(4220)

**Comment by Arco-Dielhof** [comment]
Sadly I did not have time to look into this yet, but will do so tomorrow, now that I am finally not stuck to my bed anymore.

**Comment by Arco-Dielhof** [comment]
Should be fixed in next update.
